### PR TITLE
JBIDE-18772: Fix artifact name for publish

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
@nickboldt  Would you mind to review it?

**Comment by nickboldt** [comment]
So, we're producing & publishing two zips now, one of which is tied to a Jenkins variable? Hmm. This seems bad.

Since VERSION is:
      VERSION=`cat ${WORKSPACE}/sources/pom.xml | egrep -A1 "<parent>|>parent" | grep version | sed -e "s#.\+>\([^<>]\+\)<.\+#\1#" -e "s#-SNAPSHOT##"`

Maybe we want to pull from parent pom version via maven variable instead of clunky shell script cat/grep hack?

**Comment by nickboldt** [comment]
Simpler approach using maven vars and producing only 1 zip, not three:
https://github.com/jbosstools/jbosstools-browsersim/pull/67

**Comment by mickaelistria** [comment]
Replaced by #67

**Pull request closed without merging**
